src/components/Search.vue, src/components/paginate/PaginateModule.vue, src/components/results/Entreprise.vue, src/components/results/Results.vue, src/components/searchbars/SearchBar.vue, src/components/searchbars/SearchBarSmall.vue, src/main.js
Moved the store import to root so it can be accessible from all components.
=> improve: import store at root

src/components/Entreprise.vue, src/components/Results.vue, src/components/mixins/filters.js, src/components/paginate/PaginateModule.vue, src/style/_variables.scss
Added TVA intracommunautaire in computed properties for page Result
=> Ajout calcul TVA intracommunautaire

src/components/Navbar.vue, src/components/search/SearchBar.vue
Fix #18 
The content of the main search bar is now linked to the content in store.
Clicking on the logo clear the homepage and the main search bar content.
=> Click on logo now reset search 

src/components/Entreprise.vue, src/components/Navbar.vue, src/components/paginate/PaginateModule.vue, src/components/search/SearchBar.vue, src/store/modules/search.js, src/store/modules/welcomeText.js
fix #31 
Added search by siret : using a siret in search field will now send to /entreprise/:siret page.
Also added function goToClearedHomePage, useful for some cases.
=> Added search by siret

src/components/Entreprise.vue, src/components/Results.vue, src/components/mixins/filters.js
=> clean spaced names

src/store/modules/categories.js
Small change to revert a bad correction from last review
=> hot fix for categories broken by small changes

config/dev.env.js, config/prod.env.js, src/constants.js, src/main.js, src/store/modules/search.js
Fix #44 
Canceled previous changes,
Changed constants according to our last meeting (in environment files).
=> Cleaner constants

package.json, src/components/search/SearchBar.vue
=> Added debouncing of search by searchbar

build/webpack.base.conf.js, package-lock.json, package.json
Id prefer to keep the license files so adding this change doesn't take much
=> Added ignore loader to ignore loading of text files

src/components/FooterEtalab.vue, src/components/home/Api.vue, src/components/home/PublicAdministration.vue
Adding functional links on homepage will make the website look better immediately at a small cost.
I'm not 100% sure I have picked the right links to display. I added links to what the user would expect or want, but it might not be the best choices.
=> Adding links on homepage and footer

src/components/Etablissement.vue, src/components/Search.vue, src/components/search/SearchCategories.vue, src/style/_base.scss, src/style/_variables.scss
=> style: company page

src/App.vue, src/components/Etablissement.vue, src/components/etablissement/EtablissementPanelChildren.vue, src/components/etablissement/EtablissementPanelContact.vue, src/components/etablissement/EtablissementPanelInfo.vue, src/constants.js, src/store/index.js, src/store/modules/resultsSiren.js, src/store/modules/search.js, src/style/_panels.scss, src/style/app.scss
fix #30 
Children etablissements (with links) are on page Etablissement,d
file Etablissement.vue factorized with 2 extra components
=> Added children on page Etablissement

config/prod.env.js, index.html
fix #75 and #78 
- Viewport meta-tag allow for better experience on mobile
- SEO meta-tag allow for better experience when sharing the website adress
Facebook share:
Twitter share:
=> added meta tags viewport/SEO

src/components/FlashNotice.vue, src/components/Search.vue, src/components/mixins/suggestions.js, src/components/search/SearchBar.vue
1/ Fixed suggestion making search component change size too much (fix #73 )
2/ Fixed bug on suggestion index not being computed correctly
3/ Now resetting index of suggestions when changing fullText
4/ Preventing keydown.up default behavior putting cursor back on searchbar input
=> Better presentation for suggestions & fixing indexing bug on suggestions

config/dev.env.js, config/prod.env.js, src/components/search/SearchBar.vue
=> Changed placeholder and request paths in accordance with the new API

src/components/home/Api.vue
=> Hotfix button data.gouv on home page

index.html, src/components/search/SearchBar.vue
=> Changed title and subtitle + Added matomo tracking search

src/components/Results.vue, src/components/__tests__/__snapshots__/Results.spec.js.snap, src/store/modules/__tests__/search.spec.js, src/store/modules/search.js
=> fixed pagination bug

build/webpack.base.conf.js, package-lock.json, package.json
=> Added babel-polyfill for IE11 compatibility

build/webpack.base.conf.js, index.html, package-lock.json, package.json, src/__tests__/App.spec.js, src/components/Etablissement.vue, src/components/__tests__/Etablissement.spec.js, src/components/etablissement/EtablissementMap.vue, src/components/etablissement/__tests__/EtablissementMap.spec.js, src/components/etablissement/__tests__/__snapshots__/EtablissementMap.spec.js.snap
=> Added map on etablissement page

src/components/Etablissement.vue, src/components/Results.vue, src/components/__tests__/__snapshots__/Results.spec.js.snap, src/components/etablissement/EtablissementPanelChildren.vue
fix #116 
Important addition, but not sure about the design...
=> Added l2_normalisee in results and etablissement page

src/components/Results.vue, src/components/mixins/suggestionsHelpers.js, src/components/search/SearchBar.vue, src/components/search/__tests__/SearchBar.spec.js, src/store/modules/__tests__/results.spec.js, src/store/modules/__tests__/search.spec.js, src/store/modules/results.js, src/store/modules/search.js
=> Small fixes

src/__tests__/__snapshots__/App.spec.js.snap, src/components/FooterEtalab.vue, src/components/Results.vue, src/components/__tests__/Results.spec.js, src/components/__tests__/__snapshots__/FooterEtalab.js.snap, src/components/etablissement/EtablissementPanelInfo.vue, src/components/etablissement/__tests__/__snapshots__/EtablissementPanelInfo.spec.js.snap, src/components/home/PublicAdministration.vue, src/components/mixins/__tests__/filters.spec.js, src/components/mixins/filters.js, src/router/index.js, src/store/__mocks__/index.js
fix #138 
fix #124 
fix #137 
fix #126 
fix #127 
+ corrected wrong links in footer
=> Minor improvements

src/components/__tests__/__snapshots__/ApiDoc.spec.js.snap, src/components/apiDoc/ApiDocExample.vue, src/store/modules/__tests__/resultsSiren.spec.js, src/store/modules/resultsSiren.js
=> to put this weekend in production
Related to https://github.com/betagouv/sirene_as_api/pull/79
=> Changed etablissementChildren to adapt to new siren endpoint

index.html, src/components/etablissement/EtablissementMap.vue, src/components/etablissement/__tests__/EtablissementMap.spec.js, src/components/etablissement/__tests__/__snapshots__/EtablissementMap.spec.js.snap, src/store/modules/__tests__/results.spec.js
=> Now managing when javascript deactivated or no webgl

config/dev.env.js, config/prod.env.js, src/components/Etablissement.vue, src/components/etablissement/EtablissementMap.vue, src/components/etablissement/EtablissementPanelInfo.vue, src/components/etablissement/__tests__/EtablissementMap.spec.js, src/components/etablissement/__tests__/__snapshots__/EtablissementPanelInfo.spec.js.snap, src/components/mixins/__tests__/mapOtherMarkers.spec.js, src/components/mixins/colors.js, src/components/mixins/mapOtherMarkers.js
Added other etablissements on the map.
fix #121
=> Other etablissements markers

src/components/etablissement/EtablissementHeader.vue, src/components/etablissement/EtablissementRNA.vue, src/components/etablissement/__tests__/__snapshots__/EtablissementHeader.spec.js.snap
=> tabs in header now responsives

package-lock.json, package.json, src/App.vue, src/components/ApiDoc.vue, src/components/Etablissement.vue, src/components/Home.vue, src/components/LegalNotes.vue, src/components/Results.vue, src/components/apiDoc/ApiDocRNA.vue, src/components/apiDoc/ApiDocSirene.vue, src/components/search/SearchBar.vue, src/router/index.js
=> Title now dynamic on every pages

package-lock.json, package.json, src/App.vue, src/components/ApiDoc.vue, src/components/Etablissement.vue, src/components/Home.vue, src/components/LegalNotes.vue, src/components/Results.vue, src/components/apiDoc/ApiDocRNA.vue, src/components/apiDoc/ApiDocSirene.vue, src/components/etablissement/etablissementSirene/EtablissementSireneChildren.vue, src/components/mixins/filters.js, src/components/results/ResultsRNA.vue, src/components/results/ResultsSirene.vue, src/components/search/SearchBar.vue, src/router/index.js
=> Pluralize children

src/components/results/ResultsRNA.vue, src/components/results/ResultsSirene.vue
=> Results now clickable with middle button

src/components/etablissement/EtablissementRNCS.vue, src/components/etablissement/EtablissementSirene.vue, src/components/etablissement/etablissementRNCS/EtablissementRNCSActivity.vue, src/components/etablissement/etablissementRNCS/EtablissementRNCSGestionMorale.vue, src/components/etablissement/etablissementRNCS/EtablissementRNCSGestionPhysique.vue, src/components/etablissement/etablissementRNCS/etablissementRNCSIdentification/EtablissementRNCSPMorale.vue, src/components/etablissement/etablissementSirene/EtablissementSireneContact.vue, src/components/etablissement/etablissementSirene/EtablissementSireneInfo.vue, src/components/templates/PanelInfoRNCS.vue, src/style/_etablissement.scss
Still some work to do, maybe group managers of same role to prevent redundant roles?
=> improve rncs information display

src/components/etablissement/EtablissementHeader.vue, src/components/etablissement/EtablissementMap.vue
Prevent map from shifting to left and fix margins of API blocks
=> Fix map position

src/components/etablissement/EtablissementHeader.vue, src/components/etablissement/EtablissementMap.vue, src/components/etablissement/__tests__/__snapshots__/EtablissementHeader.spec.js.snap, src/components/etablissement/etablissementRNCS/EtablissementRNCSGestionMorale.vue, src/components/etablissement/etablissementRNCS/EtablissementRNCSGestionPhysique.vue, src/components/etablissement/etablissementRNCS/EtablissementRNCSObservations.vue, src/components/etablissement/etablissementRNCS/EtablissementRNCSRegistration.vue, src/components/etablissement/etablissementRNCS/etablissementRNCSIdentification/EtablissementRNCSPMorale.vue, src/components/etablissement/etablissementSirene/EtablissementSireneChildren.vue, src/components/mixins/formating.js
- Fixed wording for children
- Changed wording for capital
- Changed immatriculation info order
- Improved addresses display
- Added a link to moral persons SIREN
- Improved observations display
=> changes due to feedbacks

config/dev.env.js, config/prod.env.js, config/sandbox.env.js, src/components/etablissement/EtablissementMap.vue, src/components/mixins/__tests__/mapOtherMarkers.spec.js, src/components/mixins/mapOtherMarkers.js
=> Map now displaying children etablissements

src/components/etablissement/EtablissementRNCS.vue, src/components/etablissement/EtablissementSirene.vue, src/components/etablissement/etablissementRNCS/EtablissementRNCSGestionPhysique.vue, src/components/etablissement/etablissementRNCS/etablissementRNCSIdentification/EtablissementRNCSPPhysique.vue, src/components/etablissement/etablissementSirene/EtablissementSireneContact.vue, src/components/mixins/formating.js
=> concatenate names, capitalize first name and uppercase last name

src/components/search/SearchBar.vue
=> now trimming user input

src/components/mixins/filters.js
fixed #228 
Output for 700 or 700.00 =>
Output for 700 .5 =>
=> Currency now shows 2 digits after comma if there are any

src/components/mixins/suggestionsHelpers.js, src/components/search/SearchBar.vue, src/store/modules/__tests__/suggestions.spec.js, src/store/modules/suggestions.js
Suggestions working, cleaned the suggestion system, added value suggestionsAllowed to prevent suggestions popping at wrong moments
=> Fixed / better suggestions

src/components/__tests__/__snapshots__/ApiDoc.spec.js.snap, src/components/apiDoc/ApiDocIntro.vue, src/components/apiDoc/ApiDocMail.vue
=> integration of mailjet iframe

src/components/etablissement/etablissementRNCS/EtablissementRNCSRegistration.vue
=> [Fix] misspelling

package-lock.json, package.json, src/components/Etablissement.vue
update du package semble suffisant
=> Meta info: title was not updated (async)

config/dev.env.js, config/sandbox.env.js, src/__tests__/__snapshots__/App.spec.js.snap, src/components/Search.vue, src/components/__tests__/__snapshots__/Search.spec.js.snap
* Amélioration du texte de présentation du service 
* Utilisation de la "vraie" base de données (appels verrouillés sur sirene1 pour ne pas subir le switch d'IP failover pendant la phase de développement)
=> Live db usage

config/dev.env.js, config/sandbox.env.js, src/components/Etablissement.vue, src/components/Results.vue, src/components/__tests__/__snapshots__/ApiDoc.spec.js.snap, src/components/apiDoc/ApiDocList.vue, src/components/etablissement/EntrepriseIdentityRNCS.vue, src/components/etablissement/EtablissementHeader.vue, src/components/etablissement/__tests__/__snapshots__/EtablissementHeader.spec.js.snap
Remove old RNCS logic & some dead code found
Re-add router link
update snapshots
=> Remove old RNCS logic

src/__tests__/__snapshots__/App.spec.js.snap, src/components/Home.vue, src/components/__tests__/__snapshots__/ApiDoc.spec.js.snap, src/components/apiDoc/ApiDocMail.vue
=> Add newsletter to home page

src/components/etablissement/EntrepriseIdentityRNCS.vue, src/components/etablissement/etablissementRNCS/etablissementRNCSIdentification/EtablissementRNCSPMorale.vue, src/components/etablissement/etablissementRNCS/etablissementRNCSIdentification/EtablissementRNCSPPhysique.vue
=> [RNCS] Personne Physique mal affiché

config/dev.env.js, config/prod.env.js, config/sandbox.env.js, src/components/apiDoc/apiDocRNCS/ApiDocRNCSEndpoints.vue, src/components/etablissement/EntrepriseIdentityRNCS.vue, src/components/etablissement/etablissementRNCS/etablissementRNCS404.vue
* Renaming de l'endpoint (premier commit) 
* Contenu statique en cas des réception de 404 de la part des API du RNCS
Hésitez pas si vous avez des idées / remarques sur le contenu statique.
=> Page statique pour les 404 des API du RNCS

src/components/etablissement/EtablissementHeader.vue, src/components/etablissement/__tests__/__snapshots__/EtablissementHeader.spec.js.snap, src/components/etablissement/etablissementRNCS/etablissementRNCSGestion/EtablissementRNCSGestionMorale.vue, src/components/etablissement/etablissementRNCS/templates/PanelInfo.vue, src/components/etablissement/etablissementSirene/EtablissementSireneChildren.vue, src/components/etablissement/etablissementSirene/EtablissementSireneInfo.vue, src/components/mixins/filters.js
=> Pretty siren, siret & num TVA

package-lock.json, src/components/etablissement/EtablissementHeader.vue, src/store/modules/searchAdditionalInfos.js
Page RNA is not working correctly at all for now, hotfixing there
There is also an issue with siren grabbing in function searchAdditionalInfoSirene from searchAdditionalInfo.js, not urgent, will be done when I redo the logic
=> Hotfix page rna

.travis.yml, package-lock.json, package.json, src/components/etablissement/EtablissementHeader.vue, src/components/etablissement/__tests__/__snapshots__/EtablissementHeader.spec.js.snap, src/components/etablissement/etablissementHeader/EtablissementHeaderTimestamp.vue, src/components/etablissement/etablissementHeader/__tests__/EtablissementHeaderTimestamp.spec.js, src/components/etablissement/etablissementSirene/__tests__/EtablissementSireneInfo.spec.js, src/components/mixins/filters.js, src/components/results/__tests__/ResultsDidYouMean.spec.js
fix #250 
Small issue to help me get accustomed again to JS TDD, design isn't the best but since we're redoing Etablissement page I didnt insist on it.
Also fixed an internationalization problem by importing correct package
=> last update of base shown in header

src/components/apiDoc/ApiDocSirene.vue, src/components/apiDoc/apiDocSirene/ApiDocSireneEndpointsV2.vue, src/components/apiDoc/apiDocSirene/ApiDocSireneEndpointsV3.vue, src/components/apiDoc/apiDocSirene/ApiDocSireneGeneric.vue
- Ajout de la doc V3 (nouveaux endpoints) au dessus de la V2
- Precisions concernant la dépréciation de la V2
- Correction au passage des limites de requêtes
=> added v3 documentation

nightwatch.conf.js, src/assets/img/arrow_top_left.svg, src/components/etablissement/EntrepriseIdentityRNCS.vue, src/components/etablissement/EtablissementHeader.vue, src/components/etablissement/__tests__/__snapshots__/EtablissementHeader.spec.js.snap, tests/e2e/specs/etablissement/children_sirets.js, tests/e2e/specs/etablissement/header.js, tests/e2e/specs/etablissement/rna_informations.js, tests/e2e/specs/etablissement/rncs_informations.js, tests/e2e/specs/fixtures.js
fix #315 
Also fixed failing e2e tests
=> Add bodacc

package-lock.json, package.json, src/components/etablissement/EtablissementHeader.vue, src/components/etablissement/etablissementRNA/EtablissementRNAImmatriculation.vue, src/components/etablissement/etablissementRNA/EtablissementRNAInfo.vue, src/components/etablissement/etablissementRNCS/EtablissementRNCSObservations.vue, src/components/etablissement/etablissementRNCS/EtablissementRNCSRegistration.vue, src/components/etablissement/etablissementRNCS/etablissementRNCSGestion/EtablissementRNCSGestionMorale.vue, src/components/etablissement/etablissementRNCS/etablissementRNCSGestion/EtablissementRNCSGestionPhysique.vue, src/components/etablissement/etablissementRNCS/etablissementRNCSIdentification/EtablissementRNCSPMorale.vue, src/components/etablissement/etablissementRNCS/etablissementRNCSIdentification/EtablissementRNCSPPhysique.vue, src/components/etablissement/etablissementRNCS/mixins/RNCSformating.js, src/components/etablissement/etablissementRNCS/mixins/__tests__/RNCSformating.spec.js, src/components/etablissement/etablissementRNM/EtablissementRNMContact.vue, src/components/etablissement/etablissementRNM/EtablissementRNMInfo.vue, src/components/etablissement/etablissementSirene/EtablissementSireneContact.vue, src/components/etablissement/etablissementSirene/EtablissementSireneInfo.vue, src/components/etablissement/etablissementSirene/__tests__/__snapshots__/EtablissementSireneInfo.spec.js.snap, src/components/mixins/__tests__/filters.spec.js, src/components/mixins/__tests__/formating.js, src/components/mixins/filters.js, src/components/mixins/formating.js, src/components/mixins/mapOtherMarkers.js, tests/e2e/specs/etablissement/rncs_informations.js, tests/e2e/specs/fixtures.js
Cette PR est assez straightforward, la méthode dans `RNCSFormating.js` pour concaténer les informations de l'adresse est cependant incompréhensible si on ne regarde pas en haut du fichier la méthode `concatIfExist`.
=> added RNCS address of siege for personne morale

src/components/Etablissement.vue, src/components/etablissement/EtablissementMap.vue, src/components/etablissement/EtablissementNonDiffusable.vue, src/components/etablissement/__tests__/__snapshots__/EtablissementMap.spec.js.snap
Ajout d'une section quand l'établissement n'est pas diffusable.
Le lien redirige vers : https://statut-diffusion-sirene.insee.fr/
Le texte est copié de l'INSEE : https://www.sirene.fr/sirene/public/question.action?idQuestion=2883
=> Non diffusables

src/components/Etablissement.vue
=> Fix RNA error

src/router/index.js
Rediriger les anciennes routes vers les nouvelles (après refactor).
=> Redirect old URLs to new ones

src/components/layout/AppFooter.vue
=> Update contact email address in footer
